apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-app-ingress
  namespace: myapp
  annotations:
     kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hello-world-app-cluster.lun.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-app-service
            port:
              number: 80